Improve support for XDG on MacOS
sayanarijit/xplr pull request #630
Opened 2023-06-07 14:36 UTC by SolitudeSF

Im not familiar with rust, so its just an attempt to improve the situation.

2023-06-08 06:06 UTC, sayanarijit requested changes
Let's keep it as a potential solution, but let's also try alternatives.

2023-06-08 06:06 UTC, sayanarijit commented on src/app.rs
> +            Some(val) => Some(val.join("/Library/Application Support")),
```suggestion
            Some(val) => Some(val.join(".config")),
```
So we don't break existing config files.

2023-06-08 06:31 UTC, sayanarijit approved these changes

2023-06-08 06:32 UTC, sayanarijit commented
@noahmayr what do you think of it as a potential solution for https://github.com/sayanarijit/xplr/issues/627?

2023-06-08 21:05 UTC, noahmayr commented
It does seem to work (on MacOS), tested both with and without XDG_CONFIG_HOME. However I feel like using the xdg-rust crate you suggested in #627 might be better to avoid platform specific logic in xplr.

Does xdg-rust cover all usecases where dirs is used for right now?

2023-06-09 16:49 UTC, sayanarijit commented
Agree. Less platform specific code is preferable.

2023-06-09 16:59 UTC, sayanarijit commented
Merged https://github.com/sayanarijit/xplr/pull/631 since as per the doc, it shouldn't break existing config. Will re-open this pr if it does.

2023-06-09 16:59 UTC, closed without merging